### ISSUE TITLE
不要咕咕咕啊 kora!

### ISSUE THREAD

**Issue by SlimeNull** [2439905184/Connecting-words-into-sentences#1]

**Comment by 2439905184** [comment]
我最近在更新升级以前的EasyAvg框架，做视觉小说用的。拿typescript重新编写一遍。
以前用的jquery+dom渲染，做的还是细节上不行

**Comment by 2439905184** [comment]
> _No description provided._

实在是一个人精力有限

**Comment by 2439905184** [comment]
> _No description provided._

在让我咕咕一会

**Comment by 2439905184** [comment]
> _No description provided._

写好了，bug不修
